parallaxsecond/parsec-book

.github/CODEOWNERS, .github/workflows/ci.yml, .gitignore, src/dev_guides/README.md, src/dev_guides/adding_provider.md, src/dev_guides/build.md, src/dev_guides/test.md, src/parsec/operations/list_opcodes.md, src/parsec/operations/list_providers.md
This commit adds updates to the developer guides part of the docs, bringing
them up to speed with the state of the service.
It also adds a GitHub Actions workflow that builds and publishes the
documentation after each push to master.
closes #1
=> Update dev guides; Add self-publishing workflow

src/parsec_service/install_parsec_linux.md
This commit updates an obsolete testing command in the Linux installation
page.
=> Update test command

src/parsec_client/operations/list_providers.md, src/parsec_client/operations/ping.md, src/parsec_client/status_codes.md, src/parsec_client/wire_protocol.md
Precises the goal of each version in Parsec. See
parallaxsecond/parsec#105 for more details.
=> Add precisions about versioning

src/SUMMARY.md, src/api_coverage.md, src/parsec_client/operations/psa_asymmetric_sign.md, src/parsec_client/operations/psa_asymmetric_verify.md, src/parsec_client/operations/psa_create_key.md
This commit adds information about the current level of progress made
against mapping the PSA crypto API as an IPC API.
Page can be seen [here](https://github.com/parallaxsecond/parsec-book/blob/fc2b162b80093dda5ecea912bd161b567b3b8bbc/src/api_coverage.md)
=> Create PSA crypto coverage page

src/api_coverage.md
This commit replaces the emojis on the coverage page with their UTF-8
equivalents.
=> Use UTF-8 characters in coverage page

src/threat_model/rust_client_threat_model.md
This commit adds details to the (un)mitigations presented in the Rust
Parsec client.
=> Add details to (un)mitigations

src/SUMMARY.md, src/clients_api_coverage.md, src/parsec_client/operations/psa_algorithm.md, src/parsec_client/operations/psa_key_attributes.md, src/service_api_coverage.md
This commit adds a new page to the book describing the API coverage of
the client libraries.
=> Add clients API coverage page

src/parsec_client/operations/list_providers.md, src/parsec_service/test.md
The ListProviders now returns providers in order of priority.
See parallaxsecond/parsec-se-driver#7 for details.
=> Add a notion of priority in ListProviders

src/parsec_service/install_parsec_linux.md
* move the commands needing `sudo` at the beginning so that they are done by the admin
* inform that rust might need to be installed in the `parsec` user
* add an example command to add an user to the `parsec-clients` group
* inform that log-out/log-in might be needed
* inform that priviliges might need to be set for the `parsec` user
=> Update the installation guide

src/SUMMARY.md, src/contributing/README.md, src/contributing/pr_checklist.md
This commit adds an informal checklist for PR reviewers. This is a brief
list of things reviewers should be aware of, but not with strict
enforcement.
=> Add PR reviewer checklist

src/parsec_service/build_run.md, src/parsec_service/install_parsec_linux.md, src/parsec_service/listeners.md
See https://github.com/parallaxsecond/parsec/issues/250 for details. Very early version now just for early feedback.
=> Update instraction after installation path changes

src/SUMMARY.md, src/contributing/README.md, src/contributing/package_management.md
This commit adds a guide for contributors who look to upstream one of
the projects under the Parsec umbrella.
=> Add upstreaming guide

src/parsec_client/api_overview.md
This commit adds a section on the API Overview page to indicate the
existance of a service discovery mechanism using the
PARSEC_SERVICE_ENDPOINT environment variable.
=> Add section on service discovery

src/parsec_client/operations/psa_aead_decrypt.md, src/parsec_client/operations/psa_aead_encrypt.md, src/parsec_client/operations/psa_algorithm.md, src/parsec_client/operations/psa_export_key.md, src/parsec_client/operations/psa_export_public_key.md, src/parsec_client/operations/psa_generate_key.md, src/parsec_client/operations/psa_key_attributes.md
Which is the newest version of PSA Crypto.
Part of #90
Note that PSA Crypto 1.0.1 also added `PSA_ALG_SM3` and `PSA_KEY_TYPE_SM4` (full diff [here](https://armmbed.github.io/mbed-crypto/html/appendix/history.html)).
If we wanted to support those new alg/key type, we would have to modify our contract to add new variants in the `oneof` field. I am not sure if adding it would be a breaking change or not ([related](https://developers.google.com/protocol-buffers/docs/proto3#oneof)). It will definitely be a breaking change in the Parsec Rust Interface as those as strongly typed enums but it might be fine there? Maybe worth opening an issue for it.
=> Fix formatting and add clarifications from 1.0.1

src/parsec_client/operations/psa_key_attributes.md, src/parsec_client/operations/psa_sign_message.md, src/parsec_client/operations/psa_verify_message.md
Specifically for signing/verifying hashes/messages.
=> Fix and add information around policies

src/parsec_service/stability.md
I had forgotten about it but hearing people using a dynamically linked version of Mbed Crypto reminded me of the need for this.
=> Add environment var as a stability requirement

src/contributing/package_management.md
This commit adds documentation to the Package Management page to help
developers publish Docker images.
=> Add documentation for publishing Docker images

src/contributing/pr_checklist.md
This commit adds a policy describing the types of tests expected for new
functionality added in a PR.
Fixes #117
=> Add testing policy

src/parsec_service/stability.md
See https://github.com/parallaxsecond/rust-psa-crypto/pull/88 for details.
=> Remove stability guarantee of Mbed Crypto/Mbed TLS

src/README.md, src/SUMMARY.md, src/parsec_client/operations/README.md, src/parsec_client/operations/attest_key.md, src/parsec_client/operations/attest_key_params.md, src/parsec_client/operations/prepare_key_attestation.md, src/parsec_client/operations/prepare_key_attestation_params.md, src/parsec_client/operations/service_api_coverage.md
This commit adds documentation for two new operations: AttestKey, used
for generating proofs that some key provisioned through Parsec is indeed
by the claimed hardware; GetMakeCredParams, used to prepare the
parameters for one of the mechanisms used within AttestKey (namely,
ActivateCredential in the TPM provider).
=> Add key attestation operations

src/SUMMARY.md, src/parsec_client/operations/README.md, src/parsec_client/operations/can_do_crypto.md, src/parsec_client/operations/service_api_coverage.md
Added the page for the CanDoCrypto operation and also added the operation to the list of operations and to the table of operations coverage
Signed-off-by: Sam Davis <sam.davis@arm.com>
=> Added CanDoCrypto operation

src/parsec_client/operations/can_do_crypto.md
Added the line describing the cause of the CanDoCrypto operation returning PsaErrorNotSupported.
Signed-off-by: Sam Davis <sam.davis@arm.com>
=> Added the PsaErrorNotPermitted line to CanDoCrypto

src/parsec_client/operations/service_api_coverage.md
The PKCS11 provider was enabled with generate random function
with #613 PR in parsec repo and TPM with #595. This patch reflects
the same in the document.
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>
=> Update api coverage with pkcs11 generate random support

src/SUMMARY.md
Previous PR caused broken links because the new subsections of the getting started guide were not included in the summary markdown.
Signed-off-by: Paul Howard <paul.howard@arm.com>
=> Add the new Quickstart pieces to the SUMMARY markdown

src/getting_started/docker.md, src/getting_started/installation_options.md, src/getting_started/parsec_tool_use.md, src/parsec_service/build_run.md, src/parsec_service/stability.md
This commit contains the following changes:
- The quickstart pages just have links to the installation guide. These are removed and installation page is renamed.
- References to 1.1.0 release is changed to 1.2.0
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>
=> Update quickstart info and release version

src/SUMMARY.md, src/contributing/release_checklist.md, src/contributing/release_process.md
This commit adds the checklist containing specific tasks to be completed in stage of the release and the testing strategy which defines the hardware/backends that are used to for running the tests.
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>
=> Add release checklist and testing information

src/overview.md, src/parsec_client/operations/psa_asymmetric_decrypt.md, src/parsec_client/operations/psa_cipher_decrypt.md
Adding `PsaErrorInvalidPadding` and a related warning on
`psa_asymmetric_decrypt` and `psa_cipher_decrypt` to notify clients of
the need for mitigations.
=> Add invalid padding warnings to decryption ops

.github/workflows/deploy.yml
18.04 has been deprecated. Change to 22.04 LTS
=> Update the Ubuntu version of the Book's Github Runner for deployment

src/getting_started/installation_options.md, src/parsec_service/build_run.md, src/parsec_service/stability.md
Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>
=> Change parsec version to 1.3.0

src/getting_started/parsec_tool_use.md, src/parsec_service/build_run.md
- Correct information on cross compilation
- Change git clone to use https and NOT ssh
=> Improvements on documentation

src/parsec_security/parsec_threat_model/threat_model.md
Add assumptions and mitigations to the attacker:
* Assumption: For a hardware attacker, it does not make sense to assume as a mitigation that the SOFTWARE configuration has been done with correct permissions. We replace it with a HARDWARE assumption that only trusted agents can physically access the system.
* Asset: We add the key mappings (and the wrapped TPM key) as a Hardware Result asset involved with this attacker.
=> threat_model: Update Hardware Result Attacker
