parallaxsecond/parsec-book

src/parsec/operations/README.md, src/parsec/operations/add_client.md, src/parsec/operations/key_attributes.md, src/parsec/operations/list_opcodes.md, src/parsec/operations/list_providers.md, src/parsec/operations/ping.md, src/parsec/operations/prove_client.md, src/parsec/operations/psa_asymmetric_sign.md, src/parsec/operations/psa_asymmetric_verify.md, src/parsec/operations/psa_create_key.md, src/parsec/operations/psa_destroy_key.md, src/parsec/operations/psa_export_public_key.md, src/parsec/operations/psa_import_key.md, src/parsec/operations/share_trust_bundle.md
This commit improves the documentation of the operations supported by Parsec,
aligning the docs to the current state of the service
=> Improve operations documentation

src/parsec_service/providers.md
=> Add some information about install TSS

src/api_coverage.md, src/parsec_client/operations/psa_asymmetric_sign.md, src/parsec_client/operations/psa_asymmetric_verify.md, src/parsec_client/operations/psa_create_key.md, src/parsec_client/operations/psa_destroy_key.md, src/parsec_client/operations/psa_export_public_key.md, src/parsec_client/operations/psa_import_key.md
=> Fix dead links

src/parsec_client/operations/list_opcodes.md, src/parsec_client/operations/psa_import_key.md, src/parsec_client/wire_protocol.md
Adds one update about the key_bits field when importing key and one
about the change to the ListOpcodes operation.
=> Add various updates

src/parsec_client/writing_library.md, src/parsec_service/build_run.md, src/parsec_service/install_parsec_linux.md, src/parsec_service/test.md, src/parsec_users.md
Specifies the clients and their current state. Makes the guides
up-to-date and easier to reproduce.
=> Make guides up-to-date

src/api_coverage.md, src/parsec_users.md
=> Update TPM API coverage

src/parsec_client/operations/psa_algorithm.md, src/parsec_service/build_run.md, src/parsec_service/test.md
=> Add info about building TPM/PKCS11 providers

src/api_coverage.md, src/parsec_client/operations/psa_asymmetric_decrypt.md, src/parsec_client/operations/psa_asymmetric_encrypt.md
=> Added asymmetric encrypt and decrypt operation pages.

src/parsec_client/operations/psa_asymmetric_decrypt.md, src/parsec_client/operations/psa_asymmetric_encrypt.md
=> Adjusted asymmetric encrypt and derypt opcodes

src/SUMMARY.md, src/clients_api_coverage.md, src/parsec_client/operations/README.md, src/service_api_coverage.md
=> Added asymmetric encrypt and decrypt to side bar

src/clients_api_coverage.md, src/parsec_client/operations/README.md, src/parsec_client/operations/psa_asymmetric_decrypt.md, src/parsec_client/operations/psa_asymmetric_encrypt.md, src/parsec_client/operations/psa_export_key.md, src/service_api_coverage.md
Also tweaked opcodes for asymmetric encrypt and decrypt
=> Add export key

src/SUMMARY.md
=> Added PsaExportKey and tweaked opcodes for asymmetric encrypt and decrypt

src/parsec_service/install_parsec_linux.md
=> Directly install from crates.io

src/SUMMARY.md, src/clients_api_coverage.md, src/parsec_client/operations/psa_aead_decrypt.md, src/parsec_client/operations/psa_aead_encrypt.md, src/service_api_coverage.md
=> Added AEAD encrypt and decrypt

src/SUMMARY.md, src/clients_api_coverage.md, src/parsec_client/operations/README.md, src/parsec_client/operations/psa_raw_key_agreement.md, src/service_api_coverage.md
=> Added raw key agreement

src/threat_model/threat_model.md
=> Add details on operational mitigations

README.md, src/README.md, src/parsec_client/api_overview.md, src/parsec_client/operations/README.md, src/parsec_client/wire_protocol.md, src/parsec_service/interfaces_and_dataflow.md, src/parsec_service/source_code_structure.md, src/parsec_service/system_architecture.md
=> Remove disclaimers and notices

src/parsec_client/operations/README.md, src/parsec_client/operations/list_keys.md, src/parsec_client/operations/service_api_coverage.md
=> Add the ListKeys operation

.github/workflows/ci.yml, src/contributing/adding_new_operation_how_to.md, src/parsec_security/parsec_threat_model/threat_model.md
This commit updates the threat model to match the latest changes around
the filesystem storage of Parsec assets and the new authentication and
deployment models.
=> Update Threat Model

src/SUMMARY.md, src/parsec_client/operations/delete_client.md, src/parsec_client/operations/list_clients.md, src/parsec_client/operations/list_keys.md
=> Fix new operation pages and contract links

src/parsec_client/operations/service_api_coverage.md
This commit updates the service coverage of algorithms and introduces a
new section for ECC curve families.
=> Update service coverage

src/contributing/package_management.md
=> Remove the broken link

src/parsec_service/build_run.md
=> Add missing direct authenticator

src/parsec_service/adding_provider.md
Expands on the key management policies needed and some general updates.
Fix #91
=> Update the "Adding a new provider" page

src/README.md, src/SUMMARY.md, src/getting_started/README.md, src/getting_started/docker.md, src/getting_started/linux_x86.md
Currently only contains the part for Linux on x86, with a native
installation.
Fix #89
=> Add a Getting Started section

src/contributing/package_management.md
=> Add instructions for local docs.rs builds

src/getting_started/linux_x86.md
=> Fix getting started folder name

src/parsec_service/providers.md
This commit expands on the details about key storage as it applies to
the Mbed Crypto provider.
=> Add details about key storage for Mbed Crypto

src/SUMMARY.md, src/contributing/release_process.md
Signed-off-by: Paul Howard <paul.howard@arm.com>
=> Create a first attempt at a documented release process for Parsec.

src/parsec_client/operations/attest_key_params.md, src/parsec_client/operations/prepare_key_attestation_params.md
=> Fix linking with IDs

src/contributing/package_management.md
=> Add requirement for submodule init

src/getting_started/linux_x86.md, src/parsec_client/operations/service_api_coverage.md, src/parsec_users.md
- the quickstart guide was changed to point to the new quickstart
package
- the service API coverage was updated
- add the Java library to list of client libs
Fixes #138
Fixes #139 
cc @GowthamSureshKumar @MohamedAsaker
=> Adjust a few things post 1.0.0 release

src/getting_started/linux_x86.md
Relates: #534
Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>
=> Add section for parsec-cli-tests script in the quickstart guide

src/getting_started/linux_x86.md, src/parsec_service/build_run.md, src/parsec_service/stability.md
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>
=> Update document for 1.1.0

.gitignore, src/getting_started/installation_options.md, src/parsec_service/build_run.md, src/parsec_service/tests/README.md
Fixes #153 when merged.
The changes included in this PR update the Getting Started documentation to take into account changes introduced in https://github.com/parallaxsecond/parsec/pull/654.
This first change updates the Tarball Quickstart instructions. Additional commits will be added to this PR for the Docker instructions.
=> Updates Getting Started documentation

src/contributing/pr_checklist.md, src/contributing/release_process.md, src/parsec_service/tests/README.md
- Add code style information
- Define the release expectations
Signed-off-by: Tomás González tomasagustin.gonzalezorlando@arm.com
=>  Improve documentation (code style, release)
